name: "🔧 리팩터링 이슈"
description: "리팩터링 이슈를 생성합니다."
title: "[REFACTOR] "
labels:
  - refactor
body:
  - type: textarea
    id: description
    attributes:
      label: "리팩터링 내용"
      description: "어떤 부분을 리팩터링할지 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "리팩터링 이유"
      description: "왜 리팩터링이 필요한지 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "개선 예상 결과"
      description: "리팩터링 후 예상되는 개선 사항을 설명해주세요."
    validations:
      required: true
