name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  tag-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ steps.tag_version.outputs.new_tag }}
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/harimdev-ai
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to AI Chat Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AI_SERVER_HOST }}
          username: ${{ secrets.AI_SERVER_USERNAME }}
          password: ${{ secrets.AI_SERVER_PASSWORD }}
          script: |
            IMAGE_TAG=${{ steps.tag_version.outputs.new_tag }}
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/harimdev-ai

            docker stop harimdev-ai || true
            docker rm harimdev-ai || true
            docker pull $IMAGE_NAME:$IMAGE_TAG
            docker run -d --name harimdev-ai -p 8000:8000 \
            --network dev-network \
            --env-file /home/halim7753/env/harimdev-ai.env \
            $IMAGE_NAME:$IMAGE_TAG
