name: Build and Deploy on Tag

on:
  create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/harimdev-ai
#          AI폴더 빌드
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./AI
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy to AI Chat Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AI_SERVER_HOST }}
          username: ${{ secrets.AI_SERVER_USERNAME }}
          # 추후 SSH 변경 예정
          password: ${{ secrets.AI_SERVER_PASSWORD }}
          script: |
            # github.ref_name 변수로 태그 이름을 가져옴
            IMAGE_TAG=${{ github.ref_name }}
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/harimdev-ai

            docker stop harimdev-ai || true
            docker rm harimdev-ai || true
            docker pull $IMAGE_NAME:$IMAGE_TAG
            docker run -d --name harimdev-ai -p 8000:8000 \
            --network dev-network \
            --env-file /home/halim/portfolio/AI/.env \
            $IMAGE_NAME:$IMAGE_TAG